# Mockingbird tests Makefile
#
# Copyright (C) 2014 Jeffrey S. Perry
#
# contact: jeffsp@gmail.com

BUILD=debug

.SUFFIXES:
.PHONY: default check clean debug release

default: debug

check: all
	./test_python.py

clean:

debug:

release:
